version: '3.7'
services:
  ds:
    image: jupyter/base-notebook:latest
    container_name: jupyter-dsdb
    environment:
      # Jupyter container variables
      JUPYTER_ENABLE_LAB: 1
      # DsDb variables
      DSDB_USER: ${DSDB_USER}
      DSDB_PASSWORD: ${DSDB_PASSWORD}
      DSDB_DB: ${DSDB_DB}
      DSDB_HOST: ${DSDB_HOST}
      DSDB_PORT: ${DSDB_PORT}
      DSDB_TYPE: ${DSDB_TYPE}
    command: >
      bash -c "conda install --yes --quiet -c conda-forge redis-py
      && python -m pip install -e /home/jovyan/local_directory
      && start-notebook.sh --notebook-dir ~/local_directory --ip 0.0.0.0 --no-browser"
    ports:
        - 8888:8888
    volumes:
      - ./:/home/jovyan/local_directory
      - jupyter_conda:/opt/conda
    # depends_on:
    #   - db

  redis:
    image: redis:6
    command: [ "redis-server", "/etc/redis/conf/redis.conf" ]
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/:/etc/redis/conf
  
  redis-insights:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db

volumes:
  jupyter_conda:
  redisinsight:
